import { MEDICAL_DISCLAIMER_EN } from '../core/constants'
import {
  formatDate,
  formatDateTime,
  labelForBodyRegion,
  labelForDocumentType,
  labelForEventType,
  labelForMeasurementType,
} from '../core/format'
import type { HealthDataSnapshot, HealthEvent } from '../core/types'

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;')
}

function eventList(events: HealthEvent[]): string {
  if (events.length === 0) {
    return '<p>No events recorded.</p>'
  }

  return `<ul>${events
    .map(
      (event) =>
        `<li><strong>${escapeHtml(labelForEventType(event.type))}</strong> - ${escapeHtml(
          formatDateTime(event.occurredAt),
        )} - ${escapeHtml(labelForBodyRegion(event.bodyRegionId))}<br>${escapeHtml(event.description)}</li>`,
    )
    .join('')}</ul>`
}

export function generateDoctorReportHtml(snapshot: HealthDataSnapshot): string {
  const number = (value: number | undefined, unit: string) =>
    value === undefined ? 'Not set' : `${escapeHtml(String(value))} ${escapeHtml(unit)}`

  const recentEvents = snapshot.events.slice(0, 12)
  const recentMeasurements = snapshot.measurements.slice(0, 12)
  const recentDocuments = snapshot.documents.slice(0, 8)
  const eventsByRegion = snapshot.events.reduce<Record<string, HealthEvent[]>>((groups, event) => {
    const key = labelForBodyRegion(event.bodyRegionId)
    groups[key] = [...(groups[key] ?? []), event]
    return groups
  }, {})

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <!-- Defence in depth: the report is a static document, it never needs scripts or network access. -->
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'">
    <meta name="referrer" content="no-referrer">
    <title>MyHealthData Report</title>
    <style>
      body { color: #17211f; font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; line-height: 1.5; margin: 32px; }
      h1, h2 { color: #0f2520; }
      section { border-top: 1px solid #d8e0dc; margin-top: 24px; padding-top: 18px; }
      .notice { background: #f1f7f4; border: 1px solid #cddbd5; border-radius: 6px; padding: 12px 14px; }
      table { border-collapse: collapse; width: 100%; }
      th, td { border-bottom: 1px solid #d8e0dc; padding: 8px; text-align: left; }
    </style>
  </head>
  <body>
    <h1>MyHealthData user-generated report</h1>
    <p class="notice">${escapeHtml(MEDICAL_DISCLAIMER_EN)} This report was generated by the user from local records.</p>

    <section>
      <h2>Profile</h2>
      <p><strong>Alias:</strong> ${escapeHtml(snapshot.profile?.alias ?? 'Not set')}</p>
      <p><strong>Birth date:</strong> ${escapeHtml(snapshot.profile?.birthDate ?? 'Not set')}</p>
      <p><strong>Height:</strong> ${number(snapshot.profile?.heightCm, 'cm')}</p>
      <p><strong>Current weight:</strong> ${number(snapshot.profile?.currentWeightKg, 'kg')}</p>
      <p><strong>Known allergies:</strong> ${escapeHtml(snapshot.profile?.knownAllergies ?? 'Not set')}</p>
      <p><strong>Regular medications:</strong> ${escapeHtml(snapshot.profile?.regularMedications ?? 'Not set')}</p>
      <p><strong>Known conditions:</strong> ${escapeHtml(snapshot.profile?.knownConditions ?? 'Not set')}</p>
    </section>

    <section>
      <h2>Recent events</h2>
      ${eventList(recentEvents)}
    </section>

    <section>
      <h2>Events by body region</h2>
      ${Object.entries(eventsByRegion)
        .map(([region, events]) => `<h3>${escapeHtml(region)}</h3>${eventList(events.slice(0, 8))}`)
        .join('')}
    </section>

    <section>
      <h2>Recent measurements</h2>
      <table>
        <thead><tr><th>Date</th><th>Type</th><th>Value</th><th>Note</th></tr></thead>
        <tbody>
          ${recentMeasurements
            .map(
              (measurement) =>
                `<tr><td>${escapeHtml(formatDateTime(measurement.measuredAt))}</td><td>${escapeHtml(
                  labelForMeasurementType(measurement.type),
                )}</td><td>${escapeHtml(String(measurement.value))} ${escapeHtml(measurement.unit)}</td><td>${escapeHtml(
                  measurement.note ?? '',
                )}</td></tr>`,
            )
            .join('')}
        </tbody>
      </table>
    </section>

    <section>
      <h2>Recent documents</h2>
      <ul>
        ${recentDocuments
          .map(
            (document) =>
              `<li><strong>${escapeHtml(document.title)}</strong> - ${escapeHtml(
                labelForDocumentType(document.documentType),
              )} - ${escapeHtml(formatDate(document.documentDate))}</li>`,
          )
          .join('')}
      </ul>
    </section>

    <section>
      <h2>Notes</h2>
      <p>${escapeHtml(snapshot.profile?.personalNotes ?? 'No profile notes recorded.')}</p>
    </section>
  </body>
</html>`
}
